[tool.black]
line-length = 100

[tool.mypy]
ignore_missing_imports = true

[tool.pylint.message_control]
disable = """
    import-error,
    bad-continuation,
    missing-module-docstring,
    missing-function-docstring,
    logging-fstring-interpolation,
"""

[tool.pylint.format]
max-line-length = 100
good-names = """
    logger,
    i, j, k, n, m,
    e,
"""

[tool.isort]
line_length = 100
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = pylint, mypy, py36, py37, py38, coverage-report

[testenv:pylint]
skip_install = true
deps = pylint
commands = pylint src/

[testenv:mypy]
skip_install = true
deps = mypy
commands = mypy src/

[testenv]
extras = tests
commands = 
    coverage run --parallel -m pytest

[testenv:coverage-report]
skip_install = true
deps = coverage<5.0
commands =
    coverage combine
    coverage report

[coverage:run]
branch = true
source = featurerizer

[coverage:paths]
source =
    src/
    .tox/*/site-packages/
"""